### ISSUE TITLE
Showing more details about training.

### ISSUE THREAD

**Issue by huhk-sysu** [huggingface/knockknock#10]
Hello, sometimes I not only want to know when is the training finished, but also want to know what the result is (training loss, accuracy, F1-score, etc.). Is it possible to show these in email? It may work like this:

1.  the training function is called
2.  the training function successfully finish and return a dict like
  ```python
  {
     loss:0.1,
     acc: 90,
     F1: 89
  }
  ```
3. the decorator walk through the returned dict and report the result in the email.

If this sound reasonable to you I may provide a PR later.

Thanks!

**Comment by VictorSanh** [comment]
Hello @huhk-sysu,
Thanks for your interest!
It is currently possible to do that by returning the dict in your main function call.

For instance, here's the results I get when calling this little toy function:

```python
def truc():
    d = {'loss':0.1, 'acc': 90, 'thing': np.ones(3)}
    return d
```

(It is the notification on Slack but it is pretty much the same on email)
<img width="625" alt="Capture d’écran 2019-05-02 à 23 43 56" src="https://user-images.githubusercontent.com/16107619/57118966-b55cde00-6d34-11e9-9267-9d97d59c213d.png">

Victor

**Comment by huhk-sysu** [comment]
Thank you for the response. I should have checked the code first. 😄

**Comment by VictorSanh** [comment]
No worries. Your issue made me think that it's not really clear that it can do that. Let me update the README! Thanks for your question!
Victor
