### ISSUE TITLE
Add Telegram

### ISSUE THREAD

**Issue by skjerns** [huggingface/knockknock#2]
Telegram has this nice [python bot-API](https://github.com/python-telegram-bot/python-telegram-bot), might be interesting (and easy) to add this to the notification stack!

**Comment by VictorSanh** [comment]
Yes!
Good point! Some people I talked to pointed that out.
I'll work on it today or this weekend. In the meantime, if you feel like opening a PR, you are more than welcome!
Victor

**Comment by VictorSanh** [comment]
Telegram notifications are now possible with commit 017437d99cb042b9f7975c0023e47dea36b14190 !! 🎉

**Comment by skjerns** [comment]
that was quick!! awesome!

> [...] Telegram bots are shy [...]

haha love the description
