### ISSUE TITLE
How to include multiple recipient's email?

### ISSUE THREAD

**Issue by dsbyprateekg** [huggingface/knockknock#22]
Thank you all for this amazing library!
Is there any way to include multiple emails in recipient_email?

**Comment by VictorSanh** [comment]
Hello @dsbyprateekg,

For the moment, the email_sender doesn't support multiple recipients.
But I guess it is just a question of looping on a list which shouldn't be more than 3 or 4 lines of additional code. I would be happy to welcome a PR!

**Comment by rish-16** [comment]
@VictorSanh I'd love to work on this! Is it possible to assign it to me?

Cheers!

**Comment by dsbyprateekg** [comment]
Hi @VictorSanh , 
@rish-16  has already submitted a PR and it looks fine.
If you also find it suitable, please accept his PR.

**Comment by VictorSanh** [comment]
It has been merged in PR #23.
I'm closing this.
