### ISSUE TITLE
Adding a desktop notification for macos

### ISSUE THREAD

**Issue by atakanyenel** [huggingface/knockknock#26]
Hello , I was thinking about adding desktop notification. You know the ones that pop up on upper right corner. I have a Mac but it can be extended by others with different OS's. It doesn't require any token info, maybe couple of configuration arguments , and can simply be called with `@desktop_sender()`.

It's not a hard task, there are already libraries for it , but nevertheless I would like to make the PR myself.

What do you think ?

**Comment by VictorSanh** [comment]
Hello @atakanyenel,

Yes, I see what you are talking about! I'm not really familiar with the libraries that handle this type of notification. Is it cross-platform or a specific code has to be developed for each os (mainly: linux, mac, windows)? So far, I've tried to make as simple as possible and to integrate it with what people already use independently of this library. It would be great if it supports the main OS.

I'm also curious: how long are your training/tasks? I usually use knockknock for longer (at least a few hours) trainings so I like receiving something on my phone as I don't necessarily have my laptop with me.

Victor

**Comment by atakanyenel** [comment]
The libraries that I know of are not cross-platform but we can combine couple of libraries for each OS and check the current OS with `os.name`. 

I also understand that this case is only usable for people who train on their own computer and not on their server.

I'm also not a ML researcher and I don't do training :) What I use `knockknock` is for load testing with python or running build scripts. So I let the python script run, watch a youtube video , in 5-10 mins I would check the terminal, so  desktop notif would be enough for me. 

I can send an example implementation for macos in a PR but only if you want to have it implemented.

what do you think ?

**Comment by VictorSanh** [comment]
Gotcha, I don't why I assumed that you were doing machine learning but I am glad that this small lib can be useful if other use-cases!

I was also thinking that there are ways to configure something in bash to send notifs at the end of a process. It would be cross-platform (as long as you use terminal), but I don't think the UI is as polished as the one we are talking about (cute notifications on the top right on Mac).

If you could open a pull request, I would be happy to coordinate with you on this, and hopefully, someone else knows enough to include other platforms (Windows and Linux).

**Comment by VictorSanh** [comment]
Merged in pull request #29.
Closing this.
