### ISSUE TITLE
ModuleNotFoundError: No module named 'knockknock'

### ISSUE THREAD

**Issue by echan00** [huggingface/knockknock#28]
Something is wrong with the pip package?

**Comment by VictorSanh** [comment]
Hello @echan00,
Could you share the command you're trying to launch?
It's not clear to me where the problem is coming from.
Victor

**Comment by echan00** [comment]
I installed knockknock via pip and then:

`from knockknock import slack_sender`

**Comment by VictorSanh** [comment]
That's extremely strange.
I create a new env to try to reproduce your problem, but I couldn't.
Can you try a `pip show knockknock`?

**Comment by echan00** [comment]
Yes it is strange. Pip show knockknock showed the correct location of the distribution on my Mac.

**Comment by VictorSanh** [comment]
Could it be a permission problem? 
cf [this](https://stackoverflow.com/questions/14295680/unable-to-import-a-module-that-is-definitely-installed)

**Comment by echan00** [comment]
Nope, I only have only one user on my Mac. I installed on both python2 and python3 and both didn't work.

**Comment by VictorSanh** [comment]
I work on Mac too but still can't reproduce the problem.
Could you test in a brand new/clean environment (virtualenv, conda env, which ever you prefer...)?
I suspect it's a conflict in python or pip versions...

**Comment by echan00** [comment]
`I suspect it's a conflict in python or pip versions...`
Yes that's what it was! Thanks
