### ISSUE TITLE
Add Dingding

### ISSUE THREAD

**Issue by JetRunner** [huggingface/knockknock#30]
Dingding (DingTalk) is a very widely used IM tool in China (basically Chinese version of Slack). Could you consider implement a support for Dingding?

Here is a repo which you may directly refer to: https://github.com/zhh1115/dingtalk-webhook

Thanks!

**Comment by JetRunner** [comment]
If you do not have a plan for this, maybe I can help with it (but I cannot guarantee the time of completion)...

**Comment by VictorSanh** [comment]
Hello @JetRunner,
I am happy to promote external contributors so if you want to open a Pull Request, I would be happy to help.
I have never used DingTalk in the past and have a limited comprehension of written Chinese. So I'll need help with that.
Victor

**Comment by wuutiing** [comment]
hi @JetRunner , i created a pull request which is an implementation of what you want, see https://github.com/huggingface/knockknock/pull/38
how about it? appreciate your advices @VictorSanh
