### ISSUE TITLE
installation from conda

### ISSUE THREAD

**Issue by AgentDS** [huggingface/knockknock#4]
since I am using conda to manage my python package, could you please make it available to install this package using conda?

**Comment by VictorSanh** [comment]
Hmmm I am not actually sure what's the best way to do it.
Would publishing it to pypi help?

**Comment by AgentDS** [comment]
https://medium.com/@giswqs/building-a-conda-package-and-uploading-it-to-anaconda-cloud-6a3abd1c5c52
I mean, could you please upload the package to Anaconda cloud, so I can install this via conda command?

**Comment by AgentDS** [comment]
maybe this helps
https://docs.anaconda.com/anaconda-cloud/user-guide/tasks/work-with-packages/#uploading-packages

**Comment by VictorSanh** [comment]
It's done. You can use conda to install knockknock.
See https://anaconda.org/victorsanh/knockknock

**Comment by AgentDS** [comment]
Could you please make it available for osx-64? really appreciate it

**Comment by VictorSanh** [comment]
I'm working on that, but I have to acknowledge that conda is really giving me a hard time: it is significant less smooth than with pip...
In the meantime, you can always bypass the installation using a `python setup.py install` (it won't be tracked with the conda package manager but at least, you can use the lib as a package).

**Comment by VictorSanh** [comment]
hey @AgentDS, I uploaded the `osx-64` package! Enjoy!

**Comment by AgentDS** [comment]
thanks!
