### ISSUE TITLE
Need a CONTRIBUTING.md. (Trouble setting up repository in Mac OS)

### ISSUE THREAD

**Issue by narayanacharya6** [huggingface/knockknock#45]
I am trying to set up the repository locally on my machine (Mac OS) with virtual env and Python 3.7 but ran into an issue while trying to install 'win10toast==0.9'.

I tried using `pip3 install 'win10toast==0.9'`

Received this as an error:

```
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting win10toast==0.9
  Using cached win10toast-0.9-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: setuptools in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages (from win10toast==0.9) (40.8.0)
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
ERROR: Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->win10toast==0.9) (from versions: none)
ERROR: No matching distribution found for pywin32>=223 (from pypiwin32->win10toast==0.9)
```

Quick google searches suggested installing pypiwin32/pywin32, but they did not do the trick :( Any quick pointers?

Maybe worth putting together a setup or contributing guide for the repo?

**Comment by VictorSanh** [comment]
Oh yes indeed... I'll remove `win10toast` as a dependency, and move this import specifically if you are using Windows desktop sender.

**Comment by narayanacharya6** [comment]
Hi @VictorSanh, was this resolved? I am still having trouble setting up the repo :(

**Comment by VictorSanh** [comment]
Is it the same issue you're having? Mind copy-pasting your traceback?
You shouldn't have to install `win10toast` if you are not on Windows now: I removed it from the dependencies, and you shouldn't call it in the desktop_sender.

**Comment by narayanacharya6** [comment]
Apologies, I hadn't pulled the latest changes from upstream into my forked repo.
