### ISSUE TITLE
Update PyPi version to 0.1.8.1

### ISSUE THREAD

**Issue by setu4993** [huggingface/knockknock#49]
Thank you for keeping up the good work on creating and maintaining this project!

I can see that the version on the repo has updated to [0.1.8.1](https://github.com/huggingface/knockknock/commit/1e8d8e645e9080f8d5b99c036414c7b148c3c4f0), can the same be pushed to PyPi?

Thanks!

**Comment by VictorSanh** [comment]
Hello @setu4993, I am going to push the `0.1.8.1` in a couple of days with some PRs to merge. I got ahead of myself and changed the version before pushing it to pypi.
In the meantime, you can still install from source. Are there any changes you want to use on master?

**Comment by setu4993** [comment]
Thanks for the update, @VictorSanh. No problem. I assumed it was ready to be pushed since it was updated on `master`.

I help maintain the [knockknock feedstock](https://github.com/conda-forge/knockknock-feedstock) on conda-forge, and the 0.1.8 builds kept failing because of issues with win10toast.

**Comment by VictorSanh** [comment]
@setu4993 It's up on pypi. Thank you for maintaining it!
