### ISSUE TITLE
Add QPush

### ISSUE THREAD

**Issue by 1049451037** [huggingface/knockknock#5]
Hi, your package is really good! Besides, I think [QPush](https://gist.github.com/1049451037/cf7a046bbec6e9e019ee8a8cc28c9383) is also worth trying!

**Comment by VictorSanh** [comment]
Thank you!
Nice!
Someone pointed me to IFTTT for text notifications. Have you ever considered using IFTTT? Seems like QPush is only compatible with iOS devices and I'd like to keep knockknock cross-device.
