### ISSUE TITLE
Is there a functionality to report epoch wise loss and other metrics?

### ISSUE THREAD

**Issue by jetjodh** [huggingface/knockknock#57]
Is there a functionality to report epoch wise loss and other metrics? I am only able to get final losses and metrics but not epoch-wise updates. Can it be done via this library? I want to track the updates of model when I am away from my terminal and compute is not really affordable for me.

**Comment by eric-yates** [comment]
I don't know the answer. If it isn't already available, this would be an awesome feature to add 🙂

**Comment by casperdcl** [comment]
would require editing the current message (if the provider supports it) to avoid multi-message spam. Not supported in https://github.com/liiight/notifiers/issues/440 either.


For now, all I know of is `tqdm.contrib` ([slack](https://tqdm.github.io/docs/contrib.slack/), [discord](https://tqdm.github.io/docs/contrib.discord/), [telegram](https://tqdm.github.io/docs/contrib.telegram/)) :)
