### ISSUE TITLE
how to reset password in Keyring file?

### ISSUE THREAD

**Issue by cpoptic** [huggingface/knockknock#63]

**Comment by sangshuduo** [comment]
curious how to fix this issue as I want to do that too.

**Comment by mcnoat** [comment]
@sangshuduo I looked into yagmail's source code: The password is saved in keyring with "yagmail" as the system and the gmail address as the username. Hence, you can change it with:
```python
import keyring
keyring.set_password("yagmail", "<your_email@address.com>")
```
