### ISSUE TITLE
Typo in DATE_FORMAT

### ISSUE THREAD

**Issue by huhk-sysu** [huggingface/knockknock#7]
Hello, there seems to be a typo in DATE_FORMAT:
https://github.com/huggingface/knockknock/blob/7d5c1ff47d40b07789130b7b792faf4fe9a1bdd9/knockknock/email_sender.py#L7

The second `%d` should be `%S`, which represents seconds.

**Comment by VictorSanh** [comment]
Hi @huhk-sysu 
True, thanks for pointing that out.
I corrected it in commit 829f64de558ff3ca6f53fb82eb4f3864d51d4b0d
